use QL_BanHang
go
set dateformat dmy
go
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME ='pr_ThemKH')
	DROP PROC pr_ThemKH
GO
CREATE PROC pr_ThemKH
(
	@MsKH		CHAR(10), 
	@TENKH		NVARCHAR(30), 
	@PHAI		NCHAR(5), 
	@DIACHI		NVARCHAR(100), 
	@DIENTHOAI	VARCHAR(10)
)
AS
BEGIN
	IF EXISTS(SELECT MSKH FROM KHACHHANG WHERE MsKH = @MsKH)
		RAISERROR(N'Mã số khách hàng này đã tồn tại!', 16, 1)
	ELSE
	BEGIN
		INSERT INTO KHACHHANG(MsKH, TENKH, PHAI, DIACHI, DIENTHOAI)
			VALUES(@MsKH, @TENKH, @PHAI, @DIACHI, @DIENTHOAI)
		RAISERROR(N'Thêm khách hàng: %s - %s mới thành công!', 16, 1, @MsKH, @TENKH)
	END
END
GO
EXECUTE pr_ThemKH 'KH0102', N'Trần Thị Mơ', N'Nữ', N'12 - An Phú Đông, Q.12', '0903876534'
GO
SELECT * FROM KHACHHANG